name: CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    name: PHP Unit Test
    strategy:
      matrix:
        php: [ '8.0', '8.2' ] #PHP versions to check.
        wp: [ 'latest', '6.5' ] # WordPress version to check.
    uses: tarosky/workflows/.github/workflows/wp-unit-test.yml@main
    with:
      php_version: ${{ matrix.php }}
      wp_version: ${{ matrix.wp }}

  phplint:
    uses: tarosky/workflows/.github/workflows/phplint.yml@main
    with:
      php_versions: '["8.0","8.1","8.2"]'

  phpstan:
    name: PHPStan
    uses: tarosky/workflows/.github/workflows/phpcs.yml@main
    with:
      version: 8.0
      composer_command: analyze

  phpcs:
    name: PHP Code Sniffer
    uses: tarosky/workflows/.github/workflows/phpcs.yml@main
    with:
      version: 8.0

  short-open-tag:
    uses: tarosky/workflows/.github/workflows/php-short-open-tag.yml@main

  status-check:
    name: Status Check
    runs-on: ubuntu-latest
    if: always()
    needs: [ short-open-tag, phplint, phpstan ]
    steps:
      - uses: re-actors/alls-green@release/v1
        with:
          jobs: ${{ toJSON(needs) }}

